plugins {
    id "multiloader-loader"
    id "net.minecraftforge.gradle" version "[6.0.24,6.2)"
    id "org.spongepowered.mixin" version "0.7.+"
}

base {
    archivesName = "${mod_name}-forge"
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

jarJar.enable()

tasks.named("jarJar") {}

minecraft {
    mappings channel: "official", version: minecraft_version
    copyIdeResources = true
    reobf = false

    def at = file("src/main/resources/META-INF/accesstransformer.cfg")
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        client {
            workingDirectory file("runs/client")
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName "Client"
            mods {
                modClientRun {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory file("runs/server")
            ideaModule "${rootProject.name}.${project.name}.main"
            taskName "Server"
            mods {
                modServerRun {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory file("runs/data")
            ideaModule "${rootProject.name}.${project.name}.main"
            args "--mod", mod_id, "--all", "--output", file("src/generated/resources/"), "--existing", file("src/main/resources/")
            taskName "Data"
            mods {
                modDataRun {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources.srcDir "src/generated/resources"

dependencies {
    minecraft "net.minecraftforge:forge:${max_minecraft_version}-${forge_version}"
    annotationProcessor("org.spongepowered:mixin:0.8.7:processor")

    implementation("net.sf.jopt-simple:jopt-simple:5.0.4") { version { strictly "5.0.4" } }

    // WebSocketwebsocket_version}")
    minecraftLibrary "org.java-websocket:Java-WebSocket:${websocket_version}"
    jarJar("org.java-websocket:Java-WebSocket:[${websocket_version},3.0)")

    // Simple Voice Chat
    implementation "maven.modrinth:simple-voice-chat:forge-${svc_version}"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            fg.component(it)
        }
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        forRepositories(fg.repository)
        filter {
            includeGroup "maven.modrinth"
        }
    }
}
